# Generated by Django 4.1.7 on 2023-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=5)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('captain_name', models.CharField(max_length=30)),
                ('started_year', models.IntegerField()),
            ],
        ),
    ]
