# Generated by Django 4.1.7 on 2023-03-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team_name',
            table='team_name',
        ),
    ]
