# Generated by Django 4.1.7 on 2023-03-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_alter_team_name_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_name',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
