# Generated by Django 4.1.4 on 2023-03-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='verify_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
